'use server'

import { createClient } from '@/lib/supabase/server'
import { getUserHouseholdId, getAuthUser } from '@/lib/supabase/helpers'
import { DEFAULT_BASE_BUDGET, DEFAULT_REQUESTS } from '@/lib/constants'
import { revalidatePath } from 'next/cache'

// ── Member Management ──────────────────────────────────────────────────────

export async function getHouseholdMembers() {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()

  const { data, error } = await supabase
    .from('household_members')
    .select('*')
    .eq('household_id', householdId)
    .order('created_at', { ascending: true })

  if (error) throw new Error(`Failed to fetch members: ${error.message}`)
  return data
}

export async function generateInviteLink(): Promise<string> {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()
  const user = await getAuthUser()

  // Expire any existing pending invites for this household first
  await supabase
    .from('household_invites')
    .update({ status: 'expired' })
    .eq('household_id', householdId)
    .eq('status', 'pending')

  // Create a fresh invite (token generated by DB default)
  const { data, error } = await supabase
    .from('household_invites')
    .insert({
      household_id: householdId,
      invited_by: user?.id,
    })
    .select('token')
    .single()

  if (error) throw new Error(`Failed to create invite: ${error.message}`)
  return data.token
}

export async function removeHouseholdMember(memberId: string) {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()
  const user = await getAuthUser()

  // Can't remove yourself
  const { data: self } = await supabase
    .from('household_members')
    .select('id')
    .eq('household_id', householdId)
    .eq('user_id', user?.id)
    .single()

  if (self?.id === memberId) throw new Error('You cannot remove yourself')

  const { error } = await supabase
    .from('household_members')
    .delete()
    .eq('id', memberId)
    .eq('household_id', householdId)

  if (error) throw new Error(`Failed to remove member: ${error.message}`)
  revalidatePath('/settings')
}

// ── Invite Validation (public — used by join page) ─────────────────────────

export async function getInviteDetails(token: string) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('household_invites')
    .select('id, status, expires_at, household_id, households(name)')
    .eq('token', token)
    .single()

  if (error || !data) return null
  if (data.status !== 'pending') return null
  if (new Date(data.expires_at) < new Date()) return null

  return {
    householdName: (data.households as { name: string } | null)?.name ?? 'Your household',
    token,
  }
}

export async function seedBaseBudgetDefaults() {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()

  const items = DEFAULT_BASE_BUDGET.map((item, index) => ({
    household_id: householdId,
    name: item.name,
    default_amount: item.default_amount,
    due_day: item.due_day ?? null,
    account: item.account || null,
    priority_category: item.priority_category || null,
    frequency: item.frequency,
    auto_pay: item.auto_pay,
    pay_url: null,
    notes: item.notes ?? null,
    tags: item.tags || [],
    sort_order: index,
  }))

  const { error } = await supabase
    .from('base_budget_items')
    .insert(items)

  if (error) throw new Error(`Failed to seed base budget defaults: ${error.message}`)
}

export async function seedBudgetRequestDefaults() {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()

  const requests = DEFAULT_REQUESTS.map((item) => ({
    household_id: householdId,
    name: item.name,
    amount: item.amount,
    priority_category: item.priority_category,
    status: item.status,
    tags: item.tags || [],
    notes: item.notes || null,
  }))

  const { error } = await supabase
    .from('budget_requests')
    .insert(requests)

  if (error) throw new Error(`Failed to seed budget request defaults: ${error.message}`)
}

export async function exportAllData() {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()

  const [
    { data: settings },
    { data: baseBudgetItems },
    { data: budgetPeriods },
    { data: periodExpenses },
    { data: invoices },
    { data: budgetRequests },
    { data: periodLinkedInvoices },
    { data: periodManualIncome },
  ] = await Promise.all([
    supabase.from('settings').select('*').eq('household_id', householdId),
    supabase.from('base_budget_items').select('*').eq('household_id', householdId).order('sort_order'),
    supabase.from('budget_periods').select('*').eq('household_id', householdId).order('created_at', { ascending: false }),
    supabase.from('period_expenses').select('*').eq('household_id', householdId),
    supabase.from('invoices').select('*').eq('household_id', householdId),
    supabase.from('budget_requests').select('*').eq('household_id', householdId),
    supabase.from('period_linked_invoices').select('*'),
    supabase.from('period_manual_income').select('*').eq('household_id', householdId),
  ])

  return {
    settings,
    baseBudgetItems,
    budgetPeriods,
    periodExpenses,
    invoices,
    budgetRequests,
    periodLinkedInvoices,
    periodManualIncome,
    exportedAt: new Date().toISOString(),
  }
}

// Helper to convert camelCase to snake_case
function camelToSnake(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
}

// Convert an object's keys from camelCase to snake_case
function convertKeysToSnakeCase(obj: Record<string, unknown>): Record<string, unknown> {
  const converted: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(obj)) {
    converted[camelToSnake(key)] = value
  }
  return converted
}

export async function importData(jsonString: string) {
  const supabase = await createClient()
  const householdId = await getUserHouseholdId()

  let parsed: Record<string, unknown>
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    throw new Error('Invalid JSON format')
  }

  // Import settings
  if (parsed.settings) {
    const settingsRaw = Array.isArray(parsed.settings)
      ? parsed.settings[0]
      : parsed.settings

    if (settingsRaw) {
      const settings = convertKeysToSnakeCase(settingsRaw as Record<string, unknown>)
      const { error } = await supabase
        .from('settings')
        .upsert({
          household_id: householdId,
          tithe_percentage: settings.tithe_percentage ?? 10,
          savings_percentage: settings.savings_percentage ?? 2,
          tax_percentage: settings.tax_percentage ?? 25,
          profit_percentage: settings.profit_percentage ?? 10,
          fun_money_percentage: settings.fun_money_percentage ?? 2,
          updated_at: new Date().toISOString(),
        }, { onConflict: 'household_id' })

      if (error) throw new Error(`Failed to import settings: ${error.message}`)
    }
  }

  // Import base budget items
  if (parsed.baseBudgetItems || parsed.base_budget_items || parsed.baseBudget) {
    const rawItems = (parsed.baseBudgetItems || parsed.base_budget_items || parsed.baseBudget) as Record<string, unknown>[]

    if (Array.isArray(rawItems) && rawItems.length > 0) {
      // Clear existing items first
      await supabase
        .from('base_budget_items')
        .delete()
        .eq('household_id', householdId)

      const items = rawItems.map((raw, index) => {
        const item = convertKeysToSnakeCase(raw)
        return {
          household_id: householdId,
          name: item.name as string,
          default_amount: (item.default_amount as number) || 0,
          due_day: (item.due_day as number) ?? null,
          account: (item.account as string) || null,
          priority_category: (item.priority_category as string) || null,
          frequency: (item.frequency as string) || 'Monthly',
          auto_pay: Boolean(item.auto_pay),
          pay_url: (item.pay_url as string) || null,
          notes: (item.notes as string) || null,
          tags: Array.isArray(item.tags) ? item.tags : [],
          sort_order: (item.sort_order as number) ?? index,
        }
      })

      const { error } = await supabase.from('base_budget_items').insert(items)
      if (error) throw new Error(`Failed to import base budget items: ${error.message}`)
    }
  }

  // Import invoices
  if (parsed.invoices) {
    const rawInvoices = parsed.invoices as Record<string, unknown>[]

    if (Array.isArray(rawInvoices) && rawInvoices.length > 0) {
      await supabase
        .from('invoices')
        .delete()
        .eq('household_id', householdId)

      const invoices = rawInvoices.map((raw) => {
        const inv = convertKeysToSnakeCase(raw)
        return {
          household_id: householdId,
          client_name: (inv.client_name as string) || '',
          project_name: (inv.project_name as string) || null,
          amount: (inv.amount as number) || 0,
          status: (inv.status as string) || 'projected',
          projected_date: (inv.projected_date as string) || null,
          actual_received_date: (inv.actual_received_date as string) || null,
          month: (inv.month as string) || null,
        }
      })

      const { error } = await supabase.from('invoices').insert(invoices)
      if (error) throw new Error(`Failed to import invoices: ${error.message}`)
    }
  }

  // Import budget requests
  if (parsed.budgetRequests || parsed.budget_requests) {
    const rawRequests = (parsed.budgetRequests || parsed.budget_requests) as Record<string, unknown>[]

    if (Array.isArray(rawRequests) && rawRequests.length > 0) {
      await supabase
        .from('budget_requests')
        .delete()
        .eq('household_id', householdId)

      const requests = rawRequests.map((raw) => {
        const req = convertKeysToSnakeCase(raw)
        return {
          household_id: householdId,
          name: (req.name as string) || '',
          amount: (req.amount as number) || 0,
          priority_category: (req.priority_category as string) || 'P7: UpNext',
          status: (req.status as string) || 'requested',
          tags: Array.isArray(req.tags) ? req.tags : [],
          notes: (req.notes as string) || null,
        }
      })

      const { error } = await supabase.from('budget_requests').insert(requests)
      if (error) throw new Error(`Failed to import budget requests: ${error.message}`)
    }
  }

  // Import budget periods and their expenses
  if (parsed.budgetPeriods || parsed.budget_periods) {
    const rawPeriods = (parsed.budgetPeriods || parsed.budget_periods) as Record<string, unknown>[]

    if (Array.isArray(rawPeriods) && rawPeriods.length > 0) {
      // Clear existing periods (cascades to period_expenses, linked invoices, manual income)
      await supabase
        .from('budget_periods')
        .delete()
        .eq('household_id', householdId)

      for (const raw of rawPeriods) {
        const period = convertKeysToSnakeCase(raw)
        const oldId = period.id as string | undefined

        const { data: newPeriod, error: periodError } = await supabase
          .from('budget_periods')
          .insert({
            household_id: householdId,
            period_name: (period.period_name as string) || '',
            income_amount: (period.income_amount as number) || 0,
            deduction_overrides: (period.deduction_overrides as Record<string, unknown>) || {},
          })
          .select()
          .single()

        if (periodError) throw new Error(`Failed to import budget period: ${periodError.message}`)

        // Import period expenses that belonged to this period
        if (oldId && (parsed.periodExpenses || parsed.period_expenses)) {
          const rawExpenses = (parsed.periodExpenses || parsed.period_expenses) as Record<string, unknown>[]
          const periodExpenses = rawExpenses.filter((e) => {
            const exp = convertKeysToSnakeCase(e)
            return exp.period_id === oldId
          })

          if (periodExpenses.length > 0) {
            const expenses = periodExpenses.map((raw, index) => {
              const exp = convertKeysToSnakeCase(raw)
              return {
                period_id: newPeriod.id,
                household_id: householdId,
                base_item_id: null,
                name: (exp.name as string) || '',
                default_amount: (exp.default_amount as number) || 0,
                due_day: (exp.due_day as number) ?? null,
                account: (exp.account as string) || null,
                priority_category: (exp.priority_category as string) || null,
                frequency: (exp.frequency as string) || 'Monthly',
                auto_pay: Boolean(exp.auto_pay),
                pay_url: (exp.pay_url as string) || null,
                notes: (exp.notes as string) || null,
                tags: Array.isArray(exp.tags) ? exp.tags : [],
                pay_now: Boolean(exp.pay_now),
                transferred: Boolean(exp.transferred),
                paid: Boolean(exp.paid),
                cleared: Boolean(exp.cleared),
                amount_override: (exp.amount_override as number) ?? null,
                override_notes: (exp.override_notes as string) || null,
                is_partial: Boolean(exp.is_partial),
                sort_order: (exp.sort_order as number) ?? index,
              }
            })

            const { error } = await supabase.from('period_expenses').insert(expenses)
            if (error) throw new Error(`Failed to import period expenses: ${error.message}`)
          }
        }

        // Import manual income for this period
        if (oldId && (parsed.periodManualIncome || parsed.period_manual_income)) {
          const rawIncome = (parsed.periodManualIncome || parsed.period_manual_income) as Record<string, unknown>[]
          const periodIncome = rawIncome.filter((i) => {
            const inc = convertKeysToSnakeCase(i)
            return inc.period_id === oldId
          })

          if (periodIncome.length > 0) {
            const incomeRows = periodIncome.map((raw) => {
              const inc = convertKeysToSnakeCase(raw)
              return {
                period_id: newPeriod.id,
                household_id: householdId,
                description: (inc.description as string) || '',
                amount: (inc.amount as number) || 0,
              }
            })

            const { error } = await supabase.from('period_manual_income').insert(incomeRows)
            if (error) throw new Error(`Failed to import manual income: ${error.message}`)
          }
        }
      }
    }
  }
}
