export const DEFAULT_SETTINGS = {
  tithe_percentage: 10,
  savings_percentage: 2,
  tax_percentage: 25,
  profit_percentage: 10,
  fun_money_percentage: 2,
}

export const DEFAULT_BASE_BUDGET = [
  { name: 'EOS Fitness', default_amount: 30, due_day: 22, account: 'Owners Comp', priority_category: 'P5: Lifestyle', frequency: 'Monthly' as const, auto_pay: true, tags: ['health'] },
  { name: 'Spotify', default_amount: 20, due_day: 24, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Monthly' as const, auto_pay: true, tags: ['subscriptions'] },
  { name: 'Zoom', default_amount: 30, due_day: 28, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: false, tags: ['business'] },
  { name: 'Rent', default_amount: 3300, due_day: 1, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['housing'] },
  { name: 'T-Mobile', default_amount: 203, due_day: 19, account: 'Owners Comp', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['transportation'] },
  { name: 'Car Payment', default_amount: 1050, due_day: 26, account: 'Owners Comp', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['transportation'] },
  { name: 'Business Loan', default_amount: 100, due_day: 1, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Vespa Loan', default_amount: 280, due_day: 1, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Discover Card', default_amount: 248, due_day: 11, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Capital One Enrika', default_amount: 100, due_day: 11, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Joshua Capital One', default_amount: 145, due_day: 11, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Joshua B&H Credit Card', default_amount: 200, due_day: 13, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'], notes: 'Balance: $6000' },
  { name: 'Tax Payment', default_amount: 400, due_day: 15, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Care Credit', default_amount: 350, due_day: 19, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt', 'health'] },
  { name: 'Payboo B&H CC Enrika', default_amount: 420, due_day: 27, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Apple CC Enrika', default_amount: 600, due_day: 30, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'], notes: 'Balance: $9000' },
  { name: 'Joshua Apple CC', default_amount: 250, due_day: 30, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'Cox Cable', default_amount: 150, due_day: 6, account: 'Owners Comp', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['entertainment'] },
  { name: 'SoCal Gas', default_amount: 120, due_day: 8, account: 'Owners Comp', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['utilities'] },
  { name: 'Car Insurance', default_amount: 200, due_day: 11, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: true, tags: ['insurance'] },
  { name: 'Edison', default_amount: 180, due_day: 11, account: 'Owners Comp', priority_category: 'P1: Essentials', frequency: 'Monthly' as const, auto_pay: false, tags: ['utilities'] },
  { name: 'ASPCA', default_amount: 30, due_day: 9, account: 'Opt X', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: true, tags: ['charity'] },
  { name: 'eBay CC', default_amount: 50, due_day: 27, account: 'Owners Comp', priority_category: 'P3: Debt', frequency: 'Monthly' as const, auto_pay: false, tags: ['debt'] },
  { name: 'EverAnd Book App', default_amount: 15, due_day: 1, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Monthly' as const, auto_pay: false, tags: ['education'] },
  { name: 'Toll Roads', default_amount: 50, due_day: 1, account: 'Owners Comp', priority_category: 'P5: Lifestyle', frequency: 'Monthly' as const, auto_pay: false, tags: ['transportation'] },
  { name: 'Netflix', default_amount: 25, due_day: 6, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Monthly' as const, auto_pay: true, tags: ['entertainment'] },
  { name: 'Google Services', default_amount: 20, due_day: 1, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: false, tags: ['business'] },
  { name: 'Airtable', default_amount: 15, due_day: 5, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'Tella Video Software', default_amount: 25, due_day: 5, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'Kindle', default_amount: 15, due_day: 5, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['education'] },
  { name: 'Ghost Domains', default_amount: 40, due_day: 6, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'Canva', default_amount: 15, due_day: 6, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: false, tags: ['business'] },
  { name: 'Claude.AI', default_amount: 25, due_day: 7, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'Adobe', default_amount: 55, due_day: 10, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'ChatGPT', default_amount: 20, due_day: 13, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: true, tags: ['business'] },
  { name: 'Amazon Prime', default_amount: 20, due_day: 25, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Monthly' as const, auto_pay: false, tags: ['subscriptions'] },
  { name: 'Grocery', default_amount: 250, due_day: null, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Weekly' as const, auto_pay: false, tags: ['food'] },
  { name: 'Target', default_amount: 30, due_day: null, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Weekly' as const, auto_pay: false, tags: ['shopping'] },
  { name: 'Tesla Energy', default_amount: 45, due_day: null, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Weekly' as const, auto_pay: false, tags: ['utilities'] },
  { name: 'Self Care', default_amount: 74, due_day: null, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Weekly' as const, auto_pay: false, tags: ['health'] },
  { name: 'Rika Fun Money', default_amount: 40, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Weekly' as const, auto_pay: false, tags: ['entertainment'] },
  { name: 'Coffee', default_amount: 50, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Weekly' as const, auto_pay: false, tags: ['food'] },
  { name: 'Revive', default_amount: 20, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Weekly' as const, auto_pay: false, tags: ['health'] },
  { name: 'Amazon Budget', default_amount: 75, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Weekly' as const, auto_pay: false, tags: ['shopping'] },
  { name: 'Joshua Fun Money', default_amount: 40, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Weekly' as const, auto_pay: false, tags: ['entertainment'] },
  { name: 'Writing Useful Books', default_amount: 200, due_day: null, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Annually' as const, auto_pay: false, tags: ['education'], notes: 'March' },
  { name: 'Ecamm Live', default_amount: 180, due_day: 6, account: 'Opt X', priority_category: 'P4: Business | Education', frequency: 'Annually' as const, auto_pay: false, tags: ['business'], notes: 'March' },
  { name: 'Car Tags', default_amount: 250, due_day: null, account: 'Opt X', priority_category: 'P1: Essentials', frequency: 'Annually' as const, auto_pay: false, tags: ['transportation'], notes: 'June' },
  { name: 'Christmas Savings', default_amount: 500, due_day: null, account: 'Opt X', priority_category: 'P5: Lifestyle', frequency: 'Annually' as const, auto_pay: false, tags: ['savings'], notes: 'June' },
  { name: 'EOS Annual', default_amount: 300, due_day: null, account: 'Owners Comp', priority_category: 'P5: Lifestyle', frequency: 'Annually' as const, auto_pay: false, tags: ['health'], notes: 'April' },
  { name: 'Text Expander', default_amount: 50, due_day: 1, account: 'Owners Comp', priority_category: 'P4: Business | Education', frequency: 'Annually' as const, auto_pay: false, tags: ['business'], notes: 'June' },
]

export const DEFAULT_REQUESTS = [
  { name: 'MPC Live II Retro', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['music', 'equipment'], notes: '' },
  { name: 'MIIR Mugs', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['lifestyle'], notes: '' },
  { name: 'Yellow Shoes', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['fashion'], notes: '' },
  { name: 'Extra Crafting', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['hobby'], notes: '' },
  { name: 'St Louis Trip', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['travel'], notes: '' },
  { name: 'Giving Column', amount: 0, priority_category: 'P7: UpNext', status: 'requested' as const, tags: ['charity'], notes: '' },
]
